name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test:ember
      - name: Run Tests in rawOutput app
        run: pnpm test:ember
        working-directory: test-app-raw-output
      - id: set-matrix
        run: echo "::set-output name=matrix::$(pnpm --silent scenario-tester list --files ./scenarios.js --matrix 'pnpm qunit ./scenarios.js --filter %s:')"
        working-directory: test-app

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm test:ember

  blueprints:
    name: "Blueprints Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: pnpm node-test

  try-scenarios:
    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: ${{ matrix.command }}
        working-directory: test-app
